aug:
  image_aug: true
  masked_language_model: true
backbone: convNext
cnn:
  hidden: 512
  ks:
  - - 2
    - 2
  - - 2
    - 2
  - - 2
    - 1
  pretrained: false
  ss:
  - - 2
    - 2
  - - 2
    - 2
  - - 2
    - 1
dataloader:
  num_workers: 0
  pin_memory: true
dataset:
  data_root: D:\Workspace\python_code\ImageGenerations\images_out
  image_height: 32
  image_max_width: 512
  image_min_width: 32
  name: ha1
  train_annotation: label_train.txt
  valid_annotation: label_test.txt
device: cuda
optimizer:
  max_lr: 0.001
  pct_start: 0.1
predictor:
  beamsearch: false
quiet: false
seq_modeling: seq2seq
trainer:
  batch_size: 1
  checkpoint: ./checkpoint/transformers_checkpoint.pth
  export: ./weights/transformers.pth
  iters: 100000
  log: ./train.log
  metrics: 10000
  patience: 5
  print_every: 1
  valid_every: 1000
transformer:
  decoder_embedded: 512
  decoder_hidden: 512
  dropout: 0.1
  encoder_hidden: 512
  img_channel: 512
vocab: aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&()*+,-./:;<=>?@[\]^_`{|}~’
  '
