aug:
  image_aug: true
  masked_language_model: true
backbone: convNext
cnn:
  hidden: 256
  pretrained: true
dataloader:
  num_workers: 0
  pin_memory: true
dataset:
  data_root: D:\Data\New folder\data
  image_height: 32
  image_max_width: 512
  image_min_width: 32
  name: ha
  train_annotation: label_train.txt
  valid_annotation: label_test.txt
device: cuda
optimizer:
  max_lr: 0.0003
  pct_start: 0.1
predictor:
  beamsearch: false
pretrain: https://vocr.vn/data/vietocr/vgg_transformer.pth
quiet: false
seq_modeling: transformer
trainer:
  batch_size: 32
  checkpoint: ./checkpoint/transformers_checkpoint.pth
  export: ./weights/transformers.pth
  iters: 100000
  log: ./train.log
  metrics: 10000
  patience: 5
  print_every: 1
  valid_every: 1000
transformer:
  d_model: 256
  dim_feedforward: 2048
  max_seq_length: 1024
  nhead: 8
  num_decoder_layers: 6
  num_encoder_layers: 6
  pos_dropout: 0.1
  trans_dropout: 0.1
vocab: 'aAàÀảẢãÃáÁạẠăĂằẰẳẲẵẴắẮặẶâÂầẦẩẨẫẪấẤậẬbBcCdDđĐeEèÈẻẺẽẼéÉẹẸêÊềỀểỂễỄếẾệỆfFgGhHiIìÌỉỈĩĨíÍịỊjJkKlLmMnNoOòÒỏỎõÕóÓọỌôÔồỒổỔỗỖốỐộỘơƠờỜởỞỡỠớỚợỢpPqQrRsStTuUùÙủỦũŨúÚụỤưƯừỪửỬữỮứỨựỰvVwWxXyYỳỲỷỶỹỸýÝỵỴzZ0123456789!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~ '
weights: https://vocr.vn/data/vietocr/vgg_transformer.pth
