backbone: convNext
cnn:
    # pooling stride size
    ss:
        - [2, 2]
        - [2, 2]
        - [2, 1]
         
    # pooling kernel size 
    ks:
        - [2, 2]
        - [2, 2]
        - [2, 1]

    pretrained: True
    hidden: 256
seq_modeling: seq2seq
transformer:
    encoder_hidden: 256
    decoder_hidden: 256
    img_channel: 256
    decoder_embedded: 256
    dropout: 0.1

optimizer:
    max_lr: 0.001
    pct_start: 0.1
