# for training
pretrain: https://vocr.vn/data/vietocr/vgg_transformer.pth

# url or local path (predict)
weights: https://vocr.vn/data/vietocr/vgg_transformer.pth

backbone: convNext
cnn:
    pretrained: True
    hidden: 256
seq_modeling: seq2seq
transformer:
    encoder_hidden: 256
    decoder_hidden: 256
    img_channel: 256
    decoder_embedded: 256
    dropout: 0.1

optimizer:
    max_lr: 0.001
    pct_start: 0.1