backbone: convNext
cnn:
    ss:
        - [2, 2]
        - [2, 2]
        - [2, 1]
         
    ks:
        - [2, 2]
        - [2, 2]
        - [2, 1]

    pretrained: True
    hidden: 512
seq_modeling: seq2seq
transformer:
    encoder_hidden: 512
    decoder_hidden: 512
    img_channel: 512
    decoder_embedded: 512
    dropout : 0.0

optimizer:
    max_lr : 0.001
    pct_start: 0.1
